version: '0.1'

services:
  sql:
    image: mariadb:10.7.4 # M1 Alternative
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .env
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    # command: mysqld --sql_mode="ALLOW_INVALID_DATES" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

# docker build -f includes/system/docker/Dockerfile .
# docker run -p 80:80 -v ${PWD}:/var/www/html/master 5b16d9e69fca
  master:
    build:
      context: ./
      dockerfile: ./includes/system/docker/Dockerfile
    depends_on:
      - sql
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/master
      # - /opt/tools:/opt/tools

networks:
  default:
    name: esoftplay

volumes:
  mysql_data:
    driver: local
