#!/bin/sh

### BEGIN INIT INFO
# Provides:          esoftplay_async
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example
# Description:       Example start-stop-daemon - Debian
### END INIT INFO

NAME="esoftplay_async"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

# Include functions
set -e
if [ -f "/lib/lsb/init-functions" ]; then
  . /lib/lsb/init-functions
fi

if [ -f "/etc/init.d/functions" ]; then
  . /etc/init.d/functions
fi

start() {
  echo -n "Starting async: "
  touch /opt/async.log
  chmod 777 /opt/async.log
  dtach -n /tmp/async.socket /bin/sh /var/www/html/master/includes/system/docker/esoftplay_worker
}

stop() {
  echo -n "stopping async: "
  if [ -S "/tmp/async.socket" ]; then
    pkill dtach
  fi
  # kill $(ps aux | grep dtach | awk '{print $2}')
  # dtach -a /tmp/async.socket -e '^C'
}

status() {
  if [ -S "/tmp/async.socket" ]; then
    que=$(wc -l < /opt/async.log)
    cur=$(wc -l < /tmp/async.log)
    echo -n "ACTIVE async: ${que} - ${cur}"
  else
    echo -n "inactive async...."
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

echo ""
exit 0