name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Build the Docker image # push The image to the docker hub
#         run: docker build -t esoftplay/master -f ./includes/system/docker/Dockerfile .
#       - name: Docker Push
#         run: docker push esoftplay/master:latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./includes/system/docker/Dockerfile
          push: true
          tags: esoftplay/master:latest
